version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t nodeapp -f Dockerfile .

     # deploy the image
     - run: |  
         docker login --username=pinaki.best@gmail.com --password=8fe0c4d9-c792-4685-8d42-fa264e504f10 registry.heroku.com
         docker tag nodeapp registry.heroku.com/nodeapp-pinaki/web
         docker push registry.heroku.com/nodeapp-pinaki/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web --app nodeapp-pinaki
     
